FROM nikolaik/python-nodejs:python3.9-nodejs16

USER root
WORKDIR /usr/src/app

ENV PATH /usr/src/app/js/node_modules/.bin:$PATH
ENV HOST 0.0.0.0
ENV SERVER_PORT 5000
ENV SOCKETIO_REDIS_CHANNEL online-games-socketio
ENV LOG_FILE logs/record.log

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . ./

RUN npm ci --silent --prefix ./js
RUN npm run build --prefix ./js

RUN python -m whitenoise.compress ./app/static

EXPOSE 5000
CMD ["python", "online-games.py"]