version: "3.9"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: 'online-games_app_container'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - SESSION_REDIS=redis://@database:6379/1
      - REDIS_MESSAGE_QUEUE_URL=redis://@database:6379
      - REDIS_OM_URL=redis://@database:6379/0
      - REDIS_CELERY_URL=redis://@database:6379/0
      - TZ=Europe/Warsaw
    depends_on:
      - database
      - celery
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - '${OG_HOST_PORT:-5000}:5000'
  celery:
    build:
      context: ./
      dockerfile: Dockerfile.celery.prod
    environment:
      - REDIS_CELERY_URL=redis://@database:6379/0
      - REDIS_MESSAGE_QUEUE_URL=redis://@database:6379
    depends_on:
      - database
    deploy:
      mode: replicated
      replicas: 3
  database:
    image: "redislabs/redismod"
    container_name: "online-games_redis_container"
    volumes:
      - ./redis_volume:/data

# docker compose up --build --detach
